"""add 2 consists table

Revision ID: 1a89e89d6b03
Revises: 6b6322c6e920
Create Date: 2024-11-16 11:08:52.659587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '1a89e89d6b03'
down_revision: Union[str, None] = '6b6322c6e920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_consist_of',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mid'], ['medication.medication_id'], name='fd_t_consist_mid'),
    sa.ForeignKeyConstraint(['sid'], ['treatment.sid'], name='fd_t_consist_sid'),
    sa.PrimaryKeyConstraint('sid', 'mid')
    )
    op.create_table('e_consist_of',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mid'], ['medication.medication_id'], name='fd_e_consist_mid'),
    sa.ForeignKeyConstraint(['sid'], ['examination.sid'], name='fd_e_consist_sid'),
    sa.PrimaryKeyConstraint('sid', 'mid')
    )
    op.drop_column('treatment', 't_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('t_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_table('e_consist_of')
    op.drop_table('t_consist_of')
    # ### end Alembic commands ###
