"""ipid, opid nullable change

Revision ID: 6b6322c6e920
Revises: 7a7596cd6f5d
Create Date: 2024-11-14 10:43:26.998925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '6b6322c6e920'
down_revision: Union[str, None] = '7a7596cd6f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inpatient', 'ipid',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('outpatient', 'opid',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outpatient', 'opid',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('inpatient', 'ipid',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
